/imu_bmx160:
  ros__parameters:
    bus: 1
    rate_hz: 100.0
    frame_id: "imu_link"
    bias_removal: false
    bias_duration_sec: 10.0

    imu_rotation_transformation: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]

    # Manual Biases (used if bias_removal is False)
    accel_bias: [-0.39987259,  0.06733226,  0.26389121]
    gyro_bias:  [-0.00667298,  0.00397193,  0.00581356]
    
    # Sensor Variances (diagonal elements of covariance matrix)
    accel_variance: [0.1, 0.1, 0.1]
    gyro_variance: [0.0001, 0.0001, 0.0001]
    mag_variance: [0.001, 0.001, 0.001]

    mag_declination_angle: -8.03 # degress

    # Desk-side
    # mag_bias: [-61.01285996,  -39.2375789,   -14.82194342]
    # mag_transform: [  3.26122859e-03, -5.23894966e-05, -4.88445395e-05,
    #                  -5.23894966e-05,  3.30609830e-03, -1.50993383e-05,
    #                  -4.88445395e-05, -1.50993383e-05,  1.52736920e-02]
    # mag_bias: [179.19287843, 69.55003551,  -45.13393716]
    # mag_transform: [  3.29660152e-03,  2.71763175e-05,  2.08004765e-05,
    #                   2.71763175e-05,  3.31129256e-03, -1.41203912e-05,
    #                   2.08004765e-05, -1.41203912e-05,  1.49098111e-02]
    
    # home desk
    # mag_bias: [193.53510235, 85.05667351,  -46.21418204]
    # mag_transform: [ 3.40684075e-03, -1.19520720e-06, -6.02733683e-06,
    #                 -1.19520720e-06,  3.43068081e-03, -2.25663807e-05,
    #                 -6.02733683e-06, -2.25663807e-05,  1.51403122e-02]

    # # PT in hangar
    # mag_bias: [-47.83502736, -58.12118011,  -4.88089421]
    # mag_transform: [ 3.40915752e-03, -2.06529765e-05, -3.94771953e-06,
    #                 -2.06529765e-05,  3.45294048e-03, -5.60625852e-05,
    #                 -3.94771953e-06, -5.60625852e-05,  1.50055119e-02]

    # PT Flight Test
    mag_bias: [-33.4081157,  -47.47297767, -13.47426104]
    mag_transform: [3.51869606e-03, -5.66419805e-05,  7.32537405e-05,
              -5.66419805e-05,  3.65732366e-03,  5.86315147e-05,
               7.32537405e-05,  5.86315147e-05,  1.51149403e-02]

    pub_topics:
      imu: "imu/data"
      mag: "imu/mag"