analyzer_params:
  ros__parameters:
    sub_topics:
      gps_fix:
        value: "/gps/fix"
        description: "GPS fix topic"
      gps_vel:
        value: "/gps/vel"
        description: "GPS velocity topic"
      odometry:
        value: "/ekf/odom"
        description: "Odometry topic"
      filtered_imu:
        value: "/ekf/filtered_imu"
        description: "Filtered IMU topic"
