ros2_bridge:
  ros__parameters:
    log_file_path: "/home/malekpdas/.ros/log/latest/launch.log"
    launch_dir: "/home/malekpdas/ros2-ws/src/launch"
    ws_root: "/home/malekpdas/ros2-ws"
    api_port: 8000
    api_host: "localhost"
