/sensor_fusion:
  ros__parameters:
    frames:
      map_frame: 'map'
      odom_frame: 'odom'
      base_link_frame: 'base_link'
    
    sub_topics:
      imu: '/imu_bno085/data'
      mag: '/imu_bno085/mag'
      gps_fix: '/gps_zoe_m8q/fix'
      gps_vel: '/gps_zoe_m8q/vel'
      timeout_sec: 5.0
      check_rate: 10.0

    publish_acceleration: true
    
    ahrs:
      offset_samples: 100
      gain: 0.05
      gyro_range: 500.0
      accel_rejection: 10.0
      mag_rejection: 10.0
      rejection_timeout: 500
    
    kalman_filter:
      initial_pos_uncertainty: 25.0
      initial_vel_uncertainty: 1.0
      initial_bias_uncertainty: 0.01
      process_noise_pos: 0.1
      process_noise_vel: 0.01
      process_noise_bias: 0.001
      measurement_noise_pos: 25.0
      measurement_noise_vel: 0.25
    
    lp_filters:
      accel_alpha: 0.98
    
    earth:
      gravity: 9.8066
      radius: 6378137.0
      flattening: 0.0033528106647474805
      ref_pos: [34.8767172, 136.9613642, 17.54]