/imu_bno085:
  ros__parameters:
    rate_hz: 100.0
    frame_id: "imu_link"
    
    transformation:
      imu_rotation: [1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, -1.0]
      mag_decl: -8.03 # degress

    # Manual Biases (used if bias_removal is False)
    sensor_calibration:
      bias_removal: False
      bias_duration_sec: 10.0
      accel_bias:     [-1.14582811, -0.01432422,  0.05357129]
      gyro_bias:      [8.42370863e-05,  6.66060682e-05, -9.59910983e-05]
      mag_bias:       [4.82532218e-08, -9.12769731e-08, -6.33085141e-08]
      mag_transform:  [ 2.31239933e-02, -1.33933075e-04, -1.48083236e-05,
                        -1.33933075e-04,  2.34637194e-02,  1.98589239e-05,
                        -1.48083236e-05,  1.98589239e-05,  2.31128531e-02]


    # Sensor Variances (diagonal elements of covariance matrix)
    sensor_variance:
      accel: [0.1, 0.1, 0.1]
      gyro: [0.0001, 0.0001, 0.0001]
      mag: [0.001, 0.001, 0.001]