/imu_bno085:
  ros__parameters:
    rate_hz: 100.0
    frame_id: "imu_link"
    
    transformation:
      imu_rotation: [-1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
      mag_decl: -8.03 # degress

    # Manual Biases (used if bias_removal is False)
    sensor_calibration:
      bias_removal: false
      bias_duration_sec: 2.0
      accel_bias:     [0.0, 0.0, 0.0]
      gyro_bias:      [0.0, 0.0, 0.0]
      mag_bias:       [0.0, 0.0, 0.0]
      mag_transform:  [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]


    # Sensor Variances (diagonal elements of covariance matrix)
    sensor_variance:
      accel: [0.1, 0.1, 0.1]
      gyro: [0.0001, 0.0001, 0.0001]
      mag: [0.001, 0.001, 0.001]