/gps_zoe_m8q:
  ros__parameters:
    # Interface: 'i2c' or 'uart' (hardware settings are hardcoded)
    interface_type: "uart"

    rate_hz: 18.0
    frame_id: "gps_link"
    
    # Standard Deviation Defaults (used if sensor accuracy is 0/invalid)
    sensor_variance:
      # Position: [lat, lon, alt] in meters
      pos_std: [4.0, 4.0, 10.0]
      # Velocity: speed in m/s
      vel_std: [0.5]
