/mag_calibration:
  ros__parameters:
    max_samples: 50000
    min_samples: 400
    angular_bins: 6
    gap_threshold_percent: 1.0
    plot_every_n: 50

    topics:
      mag: /imu_bno085/mag
    timeout_sec: 5.0
    check_rate: 10.0